version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - ./postgres_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
    ports:
      - 5432:5432
    env_file:
      - .env

  web:
    build: .
  command: sh -c "python3 manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 atelier.wsgi"
  volumes:
    - ./host_static_volume:/app/static
  expose:
    - 8000
  env_file:
    - .env
  depends_on:
    - db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./host_static_volume:/app/static
    depends_on:
      - web
