# Generated by Django 4.2.20 on 2025-04-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtelierEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('type', models.CharField(choices=[('PR', 'Фурнитура'), ('SR', 'Услуга')], max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('image_path', models.CharField(default='default.png', max_length=100)),
            ],
        ),
    ]
